In [36]:
import numpy as np

In [37]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [38]:
data


array([[ 1, 92, 68, 81, 59],
       [43, 44, 52, 55, 57],
       [80, 81, 70, 79,  1],
       [26,  5, 96, 38, 32],
       [ 3, 11, 26, 57, 11]])

exercise 1

In [39]:
data[[1, 3]] = data[[3, 1]]

In [40]:
data

array([[ 1, 92, 68, 81, 59],
       [26,  5, 96, 38, 32],
       [80, 81, 70, 79,  1],
       [43, 44, 52, 55, 57],
       [ 3, 11, 26, 57, 11]])

exercise 2

In [41]:
data_normalization = np.round((data - np.min(data)) / (np.max(data) - np.min(data)), 2)

In [42]:
data_normalization

array([[0.  , 0.96, 0.71, 0.84, 0.61],
       [0.26, 0.04, 1.  , 0.39, 0.33],
       [0.83, 0.84, 0.73, 0.82, 0.  ],
       [0.44, 0.45, 0.54, 0.57, 0.59],
       [0.02, 0.11, 0.26, 0.59, 0.11]])

exercise 3

In [43]:
3.
data_z_score_normalization = np.round(((data - np.mean(data)) / np.std(data)), 2)

In [44]:
data_z_score_normalization

array([[-1.54,  1.53,  0.72,  1.16,  0.41],
       [-0.7 , -1.41,  1.66, -0.29, -0.5 ],
       [ 1.12,  1.16,  0.78,  1.09, -1.54],
       [-0.13, -0.09,  0.18,  0.28,  0.35],
       [-1.47, -1.2 , -0.7 ,  0.35, -1.2 ]])

exercise 4

In [45]:
vector_matrix = np.ravel(data)

In [46]:

vector_matrix

array([ 1, 92, 68, 81, 59, 26,  5, 96, 38, 32, 80, 81, 70, 79,  1, 43, 44,
       52, 55, 57,  3, 11, 26, 57, 11])

exercise 5

In [47]:
array_my = np.array(np.random.randint(1, 100, size=5))

In [48]:
array_my


array([31, 80, 83, 27, 41])

In [49]:
array2 = np.array(np.random.randint(1, 100, size=5))

In [50]:
array2

array([68, 48, 37, 26, 30])

In [51]:
np.dot(array_my, array2)

10951

Exercise 6

In [52]:
data2 = np.array(np.random.randint(1, 100, size=9)).reshape(3,3)

In [53]:
data2

array([[51,  7, 38],
       [93, 68, 37],
       [59, 53, 42]])

In [54]:
matrix_multiplication = np.dot(data[2:, 2:], data2)

In [55]:

matrix_multiplication

array([[10976,  5915,  5625],
       [11130,  7125,  6405],
       [ 7276,  4641,  3559]])

Exercise 7

In [56]:
identity_matrix = np.eye(3)

In [57]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
identity_matrix_mult2 = identity_matrix * 2

In [59]:
identity_matrix_mult2

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [60]:
np.linalg.inv(identity_matrix_mult2)

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])

exercise 8

In [61]:
eigenvalues, eigenvectors = np.linalg.eig(data[:3, :3])

In [62]:

eigenvalues

array([180.20167808 +0.j        , -52.10083904+29.66175688j,
       -52.10083904-29.66175688j])

In [63]:
eigenvectors

array([[ 0.51360306+0.j        ,  0.69874583+0.j        ,
         0.69874583-0.j        ],
       [ 0.46967528+0.j        , -0.26263487+0.50906453j,
        -0.26263487-0.50906453j],
       [ 0.71806477+0.j        , -0.19031738-0.38393983j,
        -0.19031738+0.38393983j]])

Exercise 9

In [73]:
mark = np.random.choice(data.size, 5)

In [74]:
mark

array([ 4, 21, 10,  4,  8])

In [75]:
data_matrix_copy = data[:].astype('float')

In [76]:
data_matrix_copy

array([[ 1., 92., 68., 81., 59.],
       [26.,  5., 96., 38., 32.],
       [80., 81., 70., 79.,  1.],
       [43., 44., 52., 55., 57.],
       [ 3., 11., 26., 57., 11.]])

In [77]:
data_matrix_copy.flat[mark] = np.nan

In [78]:
data_matrix_copy

array([[ 1., 92., 68., 81., nan],
       [26.,  5., 96., nan, 32.],
       [nan, 81., 70., 79.,  1.],
       [43., 44., 52., 55., 57.],
       [ 3., nan, 26., 57., 11.]])

In [79]:

missing_value_indices = np.where(np.isnan(data_matrix_copy))

In [80]:

missing_value_indices

(array([0, 1, 2, 4]), array([4, 3, 0, 1]))