Exercise1

In [30]:
import numpy as np

Exercise 2

In [31]:
zero_array = np.zeros(10)

In [32]:
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Exercise 3

In [33]:
array = np.arange(1,11)

In [34]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
array_size = array.itemsize

In [36]:
array_size

8

In [37]:
array_len = len(array)

In [38]:
array_len

10

In [39]:
output = array_len * array_size

In [40]:
output

80

Exercise 4

In [41]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Exercise 5

In [42]:
my_vector = np.arange(10, 50)

In [43]:
my_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Exercise 6

my_vector[::-1]

Exercise 7

In [45]:
array = np.array([0,1,2,3,4,5,6,7,8])

In [50]:
matrix = array.reshape(3,3)

In [52]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Exercise 8

In [53]:
some_array = ([1,2,0,0,4,0])

In [54]:
output = np.nonzero(some_array)

In [55]:
output

(array([0, 1, 4]),)

Exercise 9

In [65]:
three_dimensional_matrix = np.eye(3)

In [66]:
three_dimensional_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Exercise 10

In [80]:
matrix_five = np.full((5,5),[0, 1, 2, 3, 4])

In [81]:
matrix_five

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Exercise 11

In [84]:
my_vector2 = np.linspace(0,1,10)

In [85]:
my_vector2

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Exercise 12

In [88]:
rand_vector = np.random.rand(10)

In [89]:
rand_vector

array([0.02768959, 0.79116458, 0.33400323, 0.09103213, 0.15067725,
       0.3528438 , 0.85050972, 0.09443845, 0.01511782, 0.83372111])

Exercise 13

In [96]:
np.iinfo('int8')

iinfo(min=-128, max=127, dtype=int8)

In [97]:
np.iinfo('int32')

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [98]:
np.iinfo('int64')

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [99]:
np.finfo('float32')

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [100]:
np.finfo('float64')

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

Exercise 14

In [101]:
array = np.arange(10, dtype = 'float32')

In [102]:
array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [103]:
int_array = array.astype('int32')

In [104]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Exercise 15

In [106]:
two_dim_array = np.arange(0,25)

In [114]:
two_dim_array = two_dim_array.reshape(5,5)


In [118]:
two_dim_array


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
two_dim_array.mean(axis = 1)

array([ 2.,  7., 12., 17., 22.])

Exercise 16

In [151]:
twodim_array = np.random.randint(0,15, (3,3))

In [152]:
twodim_array

array([[11,  0,  6],
       [ 5,  3,  1],
       [11, 14,  7]])

In [153]:
twodim_array[twodim_array[:,2].argsort()]

array([[ 5,  3,  1],
       [11,  0,  6],
       [11, 14,  7]])

Exercise 17

In [166]:
an_array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]] )

In [167]:
an_array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [168]:
an_array[[0, 2]] = an_array[[2, 0]]

In [169]:
an_array

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Exercise 18

In [177]:
np.repeat ([0,1,2], [2,3,1])

array([0, 0, 1, 1, 1, 2])