In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
sequence = np.arange(1, 10)
print(sequence)

[1 2 3 4 5 6 7 8 9]


In [17]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print (matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
df = pd.DataFrame({'A': [1, 'apple', 3, 4, 'banana'], 'B': [5, 6, 7, 8, 9]})


In [19]:
print(df)

        A  B
0       1  5
1   apple  6
2       3  7
3       4  8
4  banana  9
